version: "3.8"

services:
  # Interactive shell service for development
  ragas-shell:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/bash
    stdin_open: true
    tty: true
